class AppKeys {
  static const String supbaseUrl="https://oydjpuirgaaxururbnxc.supabase.co";
  static const String supbaseApiKey="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im95ZGpwdWlyZ2FheHVydXJibnhjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzMzY4MDcsImV4cCI6MjA1NzkxMjgwN30.vX6kkJ8TYbHESL2HN7crRBcqHuCM2qD1I_q8XE-P1hg";
}